name: Update README

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 */2 * *"

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://readcc.net/index.xml'
          file: 'README.md'
          format: '- ${monthshort} ${02day} ${year} - **[${title}](${url})**'
      - uses: sarisia/actions-commit@master
